require.config({
   paths:{
       "MKCanvas":"MKCanvas",
       "CommentSpaceAllocator":"CommentSpaceAllocator",
       "CommentParser":"CommentParser",
       "CommentLoader":"CommentLoader",
       "CommentBuilder":"CommentBuilder",
       "CommentManager":"CommentManager",
       "MKPlayer":"MKPlayer",
       "ControlBar":"ControlBar",
       "MKPlayer-view":"MKPlayer-view",
       "DataSender":"DataSender",
       "MKSocket":"MKSocket",
       "run":"run"
   }
});
require(["run"],function(run){

});
